apiVersion: v1
kind: Service
metadata:
  name: LoadBalancer
spec:
  selector:
    app: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 6443
  clusterIP: 10.96.0.1
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.65.3