CREATE DATABASE wordpress;
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON wordpress.* TO 'admin'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON phpmyadmin.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
